import { expect, test } from "@playwright/test"

test("inserts, saves, reopens and fits Einstein and Debye path models", async ({ page }, info) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.setViewportSize({ width: 1600, height: 1100 })
  await page.goto("/")
  await page.getByRole("button", { name: "Load copper examples", exact: true }).click()
  await expect(page.getByRole("checkbox", { name: /^Include path \d+$/ })).toHaveCount(4)
  await expect(page.getByLabel("Path 1 σ² (Å²)", { exact: true })).toBeVisible()
  for (const index of [2, 3, 4]) await page.getByLabel(`Include path ${index}`, { exact: true }).uncheck()
  await page.getByLabel("R max (Å)", { exact: true }).fill("2.5")
  await page.getByRole("button", { name: "Insert σ² model for path 1", exact: true }).click()
  await page.getByRole("button", { name: "Apply σ² model and sync", exact: true }).first().click()
  await expect(page.getByRole("region", { name: "Artemis EXAFS fitting setup", exact: true }).getByRole("alert")).toContainText("Sample temperature")
  // The Cu₂O example gives its Cu–O first shell its own disorder parameter.
  await expect(page.getByLabel("Path 1 σ² (Å²)", { exact: true })).toHaveValue("sig2_o")
  await page.getByLabel("Path 1 sample temperature (K)", { exact: true }).fill("300")
  await page.getByLabel("Path 1 add static disorder", { exact: true }).check()
  await page.getByLabel("Path 1 static disorder (Å²)", { exact: true }).fill("0.001")
  const saved = page.waitForResponse(response => response.url().endsWith("/model") &&
    response.request().postDataJSON()?.model.paths[0].sigma2.includes("sigma2_eins"))
  await page.getByRole("button", { name: "Apply σ² model and sync", exact: true }).first().click()
  expect((await saved).ok()).toBe(true)
  const expression = "sig2_static_1 + sigma2_eins(temperature_1, theta_e_1)"
  await expect(page.getByLabel("Path 1 σ² (Å²)", { exact: true })).toHaveValue(expression)
  const insertion = page.getByRole("region", { name: "Path 1 σ² model", exact: true })
  await insertion.screenshot({ path: info.outputPath("einstein-insertion.png") })
  await page.reload()
  await page.locator(".ath-group-select").filter({ hasText: "Cu₂O · room temperature" }).last().click()
  await page.getByRole("tab", { name: "EXAFS fitting", exact: true }).click()
  await page.getByRole("button", { name: "Expand all path details", exact: true }).click()
  await expect(page.getByLabel("Path 1 σ² (Å²)", { exact: true })).toHaveValue(expression)
  let fitted = page.waitForResponse(response => response.url().endsWith("/fit-saved"))
  await page.getByRole("button", { name: "Run EXAFS fit", exact: true }).click()
  let response = await fitted
  expect(response.ok(), await response.text()).toBe(true)
  let result = (await response.json()).project.groups.find((group: { label: string }) => group.label === "Cu₂O · room temperature").artemis.history.at(-1).result
  expect(result.paths[0].sigma2_expression).toBe(expression)
  expect(result.paths[0].values.sigma2).toBeGreaterThan(0)
  await expect(page.getByRole("table", { name: "Fitted path summary", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Insert σ² model for path 1", exact: true }).click()
  await page.getByLabel("Path 1 disorder model", { exact: true }).selectOption("debye")
  await page.getByLabel("Path 1 sample temperature (K)", { exact: true }).fill("300")
  await page.getByLabel("Path 1 characteristic temperature (K)", { exact: true }).fill("350")
  await page.getByRole("button", { name: "Apply σ² model and sync", exact: true }).first().click()
  await expect(page.getByLabel("Path 1 σ² (Å²)", { exact: true })).toHaveValue("sigma2_debye(temperature_2, theta_d_1)")
  fitted = page.waitForResponse(response => response.url().endsWith("/fit-saved"))
  await page.getByRole("button", { name: "Run EXAFS fit", exact: true }).click()
  response = await fitted
  expect(response.ok(), await response.text()).toBe(true)
  result = (await response.json()).project.groups.find((group: { label: string }) => group.label === "Cu₂O · room temperature").artemis.history.at(-1).result
  expect(result.paths[0].values.sigma2).toBeGreaterThan(0)
  expect(result.paths[0].sigma2_expression).toContain("sigma2_debye")
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel("Path 1 disorder model", { exact: true }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await insertion.screenshot({ path: info.outputPath("debye-insertion-mobile.png") })
  expect(errors).toEqual([])
})
