import { expect, test } from "@playwright/test"
import { readFile, writeFile } from "node:fs/promises"
import type { AthenaProject } from "../../lib/athena"

test.use({ launchOptions: { args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] } })

test("real EXAFS fit has a readable report and preserves original downloads", async ({ page }, info) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  const fits: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  page.on("request", request => {
    if (/\/fit(?:-saved)?$/.test(request.url())) fits.push(request.url())
  })
  await page.setViewportSize({ width: 1600, height: 1100 })
  await page.goto("/")
  await page.getByRole("radio", { name: "Light theme", exact: true }).click()
  await page.getByRole("button", { name: "Load copper examples", exact: true }).click()
  await expect(page.getByRole("checkbox", { name: /^Include path \d+$/ })).toHaveCount(4)
  const fitting = page.waitForResponse(response => response.url().endsWith("/fit-saved"))
  await page.getByRole("button", { name: "Run EXAFS fit", exact: true }).click()
  const response = await fitting
  expect(response.ok()).toBe(true)
  const fitted = (await response.json()).project as AthenaProject
  const group = fitted.groups.find(item => item.label === "Cu₂O · room temperature")!
  const record = group.artemis!.history.at(-1)!
  const result = record.result
  expect(result.success).toBe(true)

  const report = page.getByRole("region", { name: "Fit report", exact: true })
  await expect(report.getByRole("heading", { name: "Fit report", exact: true })).toBeVisible()
  await expect(report.getByText("Converged", { exact: true })).toBeVisible()
  await expect(report.getByText("R factor", { exact: true })).toBeVisible()
  await expect(report.getByText("Independent points", { exact: true })).toBeVisible()
  await expect(report.getByText(String(Number(result.statistics.r_factor!.toPrecision(5))), { exact: true })).toBeVisible()
  const summary = report.getByRole("region", { name: "Fit summary", exact: true })
  await expect(summary.getByRole("img", { name: /^FEFF path preview for/ })).toHaveCount(result.paths.length)
  await expect(summary.getByRole("columnheader", { name: "CN", exact: true })).toBeVisible()
  await expect(page.locator("[data-feff-snapshot-host] canvas")).toHaveCount(0)
  const thumbnail = summary.getByRole("img", { name: /^FEFF path preview for/ }).first()
  await expect(thumbnail).toHaveJSProperty("complete", true)
  expect(await thumbnail.evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  const initialImage = await thumbnail.getAttribute("src")
  const openPreview = summary.getByRole("button", { name: /^Open 3D preview for/ }).first()
  await openPreview.click()
  const previewDialog = page.getByRole("dialog", { name: /^3D path preview/ })
  await expect(previewDialog.getByRole("button", { name: "Reset view", exact: true })).toBeEnabled()
  await expect(page.locator("[data-feff-preview-surface] canvas")).toHaveCount(1)
  await expect(page.locator("[data-feff-snapshot-host] canvas")).toHaveCount(0)
  const surface = page.locator("[data-feff-preview-surface]")
  const bounds = (await surface.boundingBox())!
  await page.mouse.move(bounds.x + bounds.width * .45, bounds.y + bounds.height * .5)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width * .7, bounds.y + bounds.height * .6, { steps: 12 })
  await page.mouse.up()
  await page.mouse.wheel(0, -70)
  await previewDialog.screenshot({ path: info.outputPath("fit-path-3d-preview.png") })
  await previewDialog.getByRole("button", { name: "Done", exact: true }).click()
  await expect(previewDialog).toHaveCount(0)
  await expect(thumbnail).not.toHaveAttribute("src", initialImage!)
  await expect(page.locator("[data-feff-snapshot-host] canvas")).toHaveCount(0)
  await expect(page.locator("[data-feff-preview-surface] canvas")).toHaveCount(0)
  const updatedImage = await thumbnail.getAttribute("src")
  await openPreview.click()
  await expect(previewDialog.getByRole("button", { name: "Reset view", exact: true })).toBeEnabled()
  await page.keyboard.press("Escape")
  await expect(previewDialog).toHaveCount(0)
  await expect(openPreview).toBeFocused()
  await expect(page.locator("[data-feff-snapshot-host] canvas")).toHaveCount(0)
  await expect(thumbnail).toHaveAttribute("src", updatedImage!)
  await expect(summary.getByText("FEFF N", { exact: true }).first()).toBeVisible()
  const parameters = report.getByRole("table", { name: "Fitted parameters", exact: true })
  await expect(parameters.getByRole("row")).toHaveCount(result.parameters.length + 1)
  for (const parameter of result.parameters) {
    await expect(parameters.getByRole("rowheader", { name: parameter.name, exact: true })).toBeVisible()
  }
  await expect(report.getByRole("heading", { name: /^Fitted paths\b/ })).toBeVisible()
  await expect(report.getByLabel("Fitted path lengths and disorder").getByRole("row")).toHaveCount(result.paths.length + 1)

  const rawText = report.getByLabel("Original Larch fit report", { exact: true })
  await expect(rawText).toHaveCount(0)
  const guide = report.locator("details").filter({ has: page.locator("summary", { hasText: "Status color guide" }) })
  const guideToggle = guide.locator(":scope > summary")
  const guideNote = guide.getByText(/Status colors flag reference checks, not fit validity/)
  await expect(guide).not.toHaveAttribute("open", "")
  await expect(guideNote).toBeHidden()
  await guideToggle.focus()
  await page.keyboard.press("Enter")
  await expect(guideNote).toBeVisible()
  await guideToggle.press("Space")
  await expect(guideNote).toBeHidden()
  const screenshotStyle = "nextjs-portal { visibility: hidden; }"
  await report.screenshot({ path: info.outputPath("fit-report-desktop.png"), style: screenshotStyle })
  await summary.screenshot({ path: info.outputPath("fit-summary-desktop.png"), style: screenshotStyle })
  const downloading = page.waitForEvent("download")
  await report.getByRole("button", { name: "Download report", exact: true }).click()
  const reportPath = info.outputPath("artemis-fit-report.txt")
  await (await downloading).saveAs(reportPath)
  expect(await readFile(reportPath, "utf8")).toBe(result.report)

  const modelDownloading = page.waitForEvent("download")
  await report.getByRole("button", { name: "Download fit + model JSON", exact: true }).click()
  const modelPath = info.outputPath("artemis-fit.json")
  await (await modelDownloading).saveAs(modelPath)
  const bundle = JSON.parse(await readFile(modelPath, "utf8"))
  expect(bundle.schema).toBe("artemis-web/v1")
  expect(bundle.source).toEqual({ project_id: fitted.id, group_id: group.id, group_label: group.label })
  // JSON.stringify normalizes Python's negative-zero coordinates to zero.
  expect(bundle.result).toMatchObject(JSON.parse(JSON.stringify(result)))
  expect(bundle.request.paths.map((path: { content: string }) => path.content)).toEqual(record.model.paths.filter(path => path.enabled).map(path => path.content))
  expect(bundle.request.parameters.map((parameter: { name: string }) => parameter.name)).toEqual(record.model.parameters.map(parameter => parameter.name))
  expect(bundle.request.transform).toEqual(result.transform)

  await report.locator("summary").filter({ hasText: "Fit settings & statistics" }).click()
  await expect(report.getByText("Akaike criterion (AIC)", { exact: true })).toBeVisible()
  await report.locator("summary").filter({ hasText: "Fit settings & statistics" }).click()
  await report.locator("summary").filter({ hasText: /^Parameter correlations/ }).click()
  await report.locator("summary").filter({ hasText: /^Parameter correlations/ }).click()

  const lightThumbnail = await thumbnail.getAttribute("src")
  await page.getByRole("radio", { name: "Dark theme", exact: true }).click()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark")
  await expect(thumbnail).not.toHaveAttribute("src", lightThumbnail!)
  await expect(page.locator("[data-feff-snapshot-host] canvas")).toHaveCount(0)
  await report.screenshot({ path: info.outputPath("fit-report-dark.png"), style: screenshotStyle })
  await page.getByRole("radio", { name: "Light theme", exact: true }).click()
  await page.setViewportSize({ width: 1100, height: 1000 })
  await report.getByRole("heading", { name: "Fit report", exact: true }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  expect(await report.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await report.screenshot({ path: info.outputPath("fit-report-narrow-desktop.png"), style: screenshotStyle })
  await page.setViewportSize({ width: 390, height: 844 })
  await report.getByRole("heading", { name: "Fit report", exact: true }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  expect(await report.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  const tableWidths = await report.locator('[role="region"]:has(> table)').evaluateAll(elements => elements.map(element => ({
    label: element.getAttribute("aria-label"), width: element.clientWidth, scrollWidth: element.scrollWidth,
  })))
  await writeFile(info.outputPath("mobile-table-widths.json"), JSON.stringify(tableWidths, null, 2))
  for (const table of tableWidths.filter(item => item.label === "Fitted parameter values" || item.label === "Fitted path lengths and disorder")) {
    expect(table.scrollWidth, table.label ?? "Table").toBeLessThanOrEqual(table.width + 1)
  }
  await report.screenshot({ path: info.outputPath("fit-report-mobile.png"), style: screenshotStyle })
  await guideToggle.click()
  await expect(guideNote).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  expect(fits).toHaveLength(1)
  expect(errors).toEqual([])
})
