import { expect, test } from "@playwright/test"
import { readFile } from "node:fs/promises"

test("an uploaded CIF simulates, exports, and adds theory EXAFS to an empty project", async ({ page }) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.setViewportSize({ width: 1500, height: 1000 })
  await page.goto("/")
  await page.getByRole("tab", { name: "EXAFS fitting", exact: true }).click()
  const region = page.getByRole("region", { name: "Project CIF structures", exact: true })
  await expect(region.getByRole("button", { name: "Upload CIF", exact: true })).toBeEnabled()
  await expect(region.getByRole("button", { name: "Simulate EXAFS from CIF", exact: true })).toBeVisible()
  const source = await page.request.get("/api/backend/api/artemis/structures/13088")
  expect(source.ok()).toBe(true)
  const { cif } = await source.json() as { cif: string }
  const attachResponse = page.waitForResponse(response => /\/projects\/[^/]+\/structures$/.test(response.url()) && response.request().method() === "POST")
  const picker = page.waitForEvent("filechooser")
  await region.getByRole("button", { name: "Upload CIF", exact: true }).click()
  await (await picker).setFiles({ name: "simulation-copper.cif", mimeType: "chemical/x-cif", buffer: Buffer.from(cif) })
  const attached = await (await attachResponse).json()
  expect(attached.groups).toEqual([])
  const crystal = page.getByRole("dialog", { name: "Crystal structures", exact: true })
  await crystal.getByRole("button", { name: "Close CIF search", exact: true }).click()
  const record = attached.artemis_structures[0]
  const name = record.label || record.structure.mineral || record.structure.formula
  await region.getByRole("button", { name: `Simulate EXAFS from ${name} CIF`, exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Simulate EXAFS", exact: true })
  await expect(dialog.getByRole("combobox", { name: "Simulation crystal structure", exact: true })).toHaveValue(record.id)
  await dialog.getByRole("radio", { name: "Absorber site 1", exact: true }).check()
  await dialog.getByLabel("Simulation maximum R", { exact: true }).fill("3")
  await expect(dialog.getByRole("button", { name: "Run FEFF calculation", exact: true })).toHaveCount(0)
  await expect(dialog.getByRole("checkbox", { name: /^Select generated / })).toHaveCount(0)
  await expect(dialog.getByLabel("Simulation paths", { exact: true })).toHaveCount(0)
  const simulate = dialog.getByRole("button", { name: "Run EXAFS simulation", exact: true })
  await expect(simulate).toBeEnabled({ timeout: 60_000 })
  await expect(dialog.getByLabel("Simulation S₀²", { exact: true })).toHaveValue("0.85")
  await expect(dialog.getByRole("button", { name: "Add to data list", exact: true })).toHaveCount(0)
  const responsePromise = page.waitForResponse(response => response.url().endsWith("/simulate"))
  await simulate.click()
  const response = await responsePromise
  expect(response.ok()).toBe(true)
  const result = await response.json()
  expect(result.simulation.request.s02).toBe(0.85)
  expect(result.simulation.request.path_ids).toBeNull()
  expect(result.source.request.max_paths).toBeNull()
  expect(result.source.request.path_radius).toBe(3)
  expect(result.simulation.path_ids).toHaveLength(result.simulation.total_paths)
  expect(result.source.provenance.cif).toBe(cif)
  expect(result.k.chi).toHaveLength(401)
  await expect(dialog.getByText(/Simulation complete · 1 path ·/)).toBeVisible()
  await expect(dialog.locator('[aria-label="Simulated EXAFS k plot"] .js-plotly-plot')).toBeVisible()
  const csvDownload = page.waitForEvent("download")
  await dialog.getByRole("button", { name: "Download χ(k) CSV", exact: true }).click()
  const csv = await readFile((await (await csvDownload).path())!, "utf8")
  expect(csv).toContain("k_A^-1,chi,k_weighted_chi")
  expect(csv).toContain(result.simulation.cif_sha256)
  await dialog.getByRole("button", { name: "|χ(R)|", exact: true }).click()
  await expect(dialog.locator('[aria-label="Simulated EXAFS r plot"] .js-plotly-plot')).toBeVisible()
  const jsonDownload = page.waitForEvent("download")
  await dialog.getByRole("button", { name: "Download simulation JSON", exact: true }).click()
  const saved = JSON.parse(await readFile((await (await jsonDownload).path())!, "utf8"))
  expect(saved.k.chi).toEqual(result.k.chi)
  expect(saved.source.paths[0].content).toBe(result.source.paths[0].content)
  await page.setViewportSize({ width: 390, height: 844 })
  await simulate.scrollIntoViewIfNeeded()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await dialog.getByLabel("Simulation σ² (Å²)", { exact: true }).fill("0.007")
  await expect(dialog.getByRole("button", { name: "Download simulation JSON", exact: true })).toHaveCount(0)
  await expect(dialog.getByRole("button", { name: "Add to data list", exact: true })).toHaveCount(0)
  const project = await page.request.get(`/api/backend/api/athena/projects/${attached.id}?view=summary`)
  expect((await project.json()).groups).toEqual([])
  await dialog.getByLabel("Simulation σ² (Å²)", { exact: true }).fill("0.003")
  await simulate.click()
  const add = dialog.getByRole("button", { name: "Add to data list", exact: true })
  await expect(add).toBeEnabled()
  const addition = page.waitForResponse(response => response.url().endsWith("/simulation") && response.request().method() === "POST")
  await add.click()
  const additionResponse = await addition
  expect(additionResponse.ok()).toBe(true)
  const added = await additionResponse.json()
  expect(added.groups).toHaveLength(1)
  const theory = added.groups[0]
  expect(theory.data_type).toBe("chi")
  expect(theory.source.tags).toEqual(["theory"])
  expect(theory.energy).toEqual(result.k.x)
  expect(theory.mu).toEqual(result.k.chi)
  expect(theory.parameters.kweight).toBe(2)
  expect(theory.source.feff.provenance.cif).toBe(cif)
  expect(theory.source.simulation.request.s02).toBe(0.85)
  await expect(page.locator('#athena-data-groups [data-tag="theory"]')).toHaveText("theory")
  await page.reload()
  await expect(page.locator('#athena-data-groups [data-tag="theory"]')).toHaveText("theory")
  const theoryViewer = page.getByRole("region", { name: "EXAFS theory results", exact: true })
  await expect(theoryViewer.getByText("No fit performed", { exact: true })).toBeVisible()
  await expect(theoryViewer.locator(".js-plotly-plot")).toBeVisible()
  await expect(theoryViewer.getByRole("checkbox", { name: "Show paths", exact: true })).toBeChecked()
  await expect(theoryViewer.getByRole("region", { name: "Fit report", exact: true })).toHaveCount(0)
  await theoryViewer.getByRole("button", { name: "k space", exact: true }).click()
  const displayResponse = page.waitForResponse(response => response.url().endsWith("/simulation-view") && response.request().method() === "POST")
  await theoryViewer.getByLabel("EXAFS theory k-weight", { exact: true }).selectOption("3")
  const displayed = await displayResponse
  expect(displayed.ok()).toBe(true)
  expect((await displayed.json()).k.weight).toBe(3)
  await expect(theoryViewer.locator(".js-plotly-plot")).toBeVisible()
  const names = await theoryViewer.locator(".js-plotly-plot").evaluate(element =>
    (element as unknown as { data: { name: string }[] }).data.map(trace => trace.name.replaceAll("<br>", "")))
  expect(names).toEqual(["Total theory", "Path 1 · feff0001.dat"])
  await theoryViewer.getByRole("checkbox", { name: "Offset plot", exact: true }).check()
  await theoryViewer.getByLabel("Offset spacing", { exact: true }).fill("0.5")
  expect(await theoryViewer.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  const reopened = await page.request.get(`/api/backend/api/athena/projects/${attached.id}?view=summary`)
  expect((await reopened.json()).groups).toHaveLength(1)
  expect(errors).toEqual([])
})
