import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { expect, test, type Page } from '@playwright/test'

async function openRegistry(page: Page) {
  await page.getByRole('button', { name: 'File', exact: true }).click()
  await page.getByRole('button', { name: 'Plugin registry…', exact: true }).click()
  const panel = page.getByRole('dialog', { name: 'Plugin registry', exact: true })
  await expect(panel.getByRole('checkbox', { name: 'Enable X10C' })).toBeEnabled()
  return panel
}

test('plugin switches recover a blocked import, persist across windows, and exchange native YAML', async ({ page, browser }, info) => {
  test.setTimeout(90000)
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  let panel = await openRegistry(page)
  const toggle = panel.getByRole('checkbox', { name: 'Enable X10C' })
  if (await toggle.isChecked()) {
    const saved = page.waitForResponse(r => r.url().endsWith('/preferences/plugins') && r.request().method() === 'PUT')
    await toggle.click(); expect((await saved).ok()).toBe(true)
    await expect(toggle).not.toBeChecked()
  }
  await panel.getByRole('button', { name: 'Close registry', exact: true }).click()
  await page.getByRole('button', { name: 'Import data', exact: true }).click()
  const path = fileURLToPath(new URL('../../../backend/tests/fixtures/demeter-x10c.dat', import.meta.url))
  const picker = page.getByLabel('Choose data files', { exact: true }); await expect(picker).toBeEnabled()
  const rejected = page.waitForResponse(r => r.url().endsWith('/inspect'))
  await picker.setInputFiles(path)
  expect((await rejected).status()).toBe(400)
  const importing = page.getByRole('dialog', { name: 'Import spectra', exact: true })
  await expect(importing.getByRole('alert')).toContainText('X10C file plugin is disabled')
  await importing.getByRole('button', { name: 'File plugins…', exact: true }).click()
  panel = page.getByRole('dialog', { name: 'Plugin registry', exact: true })
  await expect(panel.getByRole('checkbox', { name: 'Enable X10C' })).toBeEnabled()
  const enabled = page.waitForResponse(r => r.url().endsWith('/preferences/plugins') && r.request().method() === 'PUT')
  await panel.getByRole('checkbox', { name: 'Enable X10C' }).click(); expect((await enabled).ok()).toBe(true)
  await expect(panel.getByRole('checkbox', { name: 'Enable X10C' })).toBeChecked()
  await panel.getByText('X10C documentation', { exact: true }).click()
  await expect(panel.getByRole('link', { name: 'Original X10C documentation' })).toBeVisible()
  await panel.screenshot({ path: info.outputPath('plugin-registry.png') })
  await panel.getByRole('button', { name: 'Return to import', exact: true }).click()
  await importing.getByRole('button', { name: 'Retry file inspection', exact: true }).click()
  await expect(importing.getByLabel('File conversion')).toContainText('X10C')
  await expect(importing.getByLabel('Imported signal preview plot').locator('.js-line').first()).toBeAttached()
  const accepted = page.waitForResponse(r => r.url().endsWith('/import'), { timeout: 30000 })
  await importing.getByRole('button', { name: 'Import spectrum', exact: true }).click()
  const result = await accepted; expect(result.ok()).toBe(true)
  const project = await result.json()
  expect(project.groups[0].energy).toHaveLength(547)
  expect(project.groups[0].processing_error).toBeNull()
  await expect(importing).not.toBeVisible()
  panel = await openRegistry(page)
  const disabled = page.waitForResponse(r => r.url().endsWith('/preferences/plugins') && r.request().method() === 'PUT')
  await panel.getByRole('checkbox', { name: 'Enable X10C' }).click(); expect((await disabled).ok()).toBe(true)
  await expect(panel.getByRole('checkbox', { name: 'Enable X10C' })).not.toBeChecked()
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin }); const other = await context.newPage()
  other.on('pageerror', e => errors.push(e.message))
  try {
    await other.goto('/')
    const otherPanel = await openRegistry(other)
    await expect(otherPanel.getByRole('checkbox', { name: 'Enable X10C' })).not.toBeChecked()
    const reenabled = page.waitForResponse(r => r.url().endsWith('/preferences/plugins') && r.request().method() === 'PUT')
    await panel.getByRole('checkbox', { name: 'Enable X10C' }).click(); expect((await reenabled).ok()).toBe(true)
    await expect(panel.getByRole('checkbox', { name: 'Enable X10C' })).toBeChecked()
    const stale = other.waitForResponse(r => r.url().endsWith('/preferences/plugins') && r.request().method() === 'PUT')
    await otherPanel.getByRole('checkbox', { name: 'Enable X10C' }).click()
    expect((await stale).status()).toBe(409)
    await expect(otherPanel.getByRole('alert')).toContainText('another window')
    await expect(otherPanel.getByRole('checkbox', { name: 'Enable X10C' })).not.toBeChecked()
    await otherPanel.getByRole('button', { name: 'Reload plugin settings' }).click()
    await expect(otherPanel.getByRole('checkbox', { name: 'Enable X10C' })).toBeChecked()
  } finally { await context.close() }
  const imported = page.waitForResponse(r => r.url().includes('/preferences/plugins/import?'))
  await panel.getByLabel('Import Athena plugin registry file').setInputFiles({ name: 'athena.plugin_registry', mimeType: 'application/x-yaml',
    buffer: Buffer.from('---\nDemeter::Plugins::X10C: 0\nDemeter::Plugins::Lytle: 1\nDemeter::Plugins::B18: 1\nDemeter::Plugins::UserReaderFixture: 1\n') })
  expect((await imported).ok()).toBe(true)
  await expect(panel.getByRole('checkbox', { name: 'Enable X10C' })).not.toBeChecked()
  await expect(panel.getByRole('checkbox', { name: 'Enable Lytle' })).toBeChecked()
  await expect(panel.getByRole('checkbox', { name: 'Enable B18', exact: true })).toBeChecked()
  await panel.getByText('Settings for 1 unavailable plugins', { exact: true }).click()
  await expect(panel.getByText('UserReaderFixture · saved as enabled')).toBeVisible()
  const download = page.waitForEvent('download')
  await panel.getByRole('link', { name: 'Export Athena registry', exact: true }).click()
  const savedPath = info.outputPath('athena.plugin_registry'); await (await download).saveAs(savedPath)
  const yaml = readFileSync(savedPath, 'utf8')
  expect(yaml).toContain('Demeter::Plugins::X10C: 0')
  expect(yaml).toContain('Demeter::Plugins::Lytle: 1')
  expect(yaml).toContain('Demeter::Plugins::B18: 1')
  expect(yaml).toContain('Demeter::Plugins::UserReaderFixture: 1')
  // Changing registry preferences never edits the spectrum or its history.
  const unchanged = await (await page.request.get(`/api/backend/api/athena/projects/${project.id}`)).json()
  expect(unchanged).toEqual(project)
  await page.reload(); panel = await openRegistry(page)
  await expect(panel.getByRole('checkbox', { name: 'Enable X10C' })).not.toBeChecked()
  await expect(panel.getByRole('checkbox', { name: 'Enable Lytle' })).toBeChecked()
  expect(errors).toEqual([])
})
