import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { expect, test, type Locator, type Page } from '@playwright/test'

const fixture = fileURLToPath(new URL('../../../backend/tests/fixtures/demeter-x11a-cu.012', import.meta.url))
const rows = readFileSync(fixture, 'utf8').split('\n').slice(12).filter(l => l.trim()).map(l => l.trim().split(/\s+/).map(Number))
async function signal(plot: Locator, y: number[]) {
  await expect(plot.locator('.js-line').first()).toBeAttached()
  await expect.poll(async () => plot.locator('.js-plotly-plot').evaluate(node => {
    const t = (node as HTMLElement & { data: { x: number[]; y: number[] }[] }).data[0]
    return [...t.x]
  })).toEqual(rows.map(r => r[0]))
  await expect.poll(async () => plot.locator('.js-plotly-plot').evaluate((node, values) => {
    const t = (node as HTMLElement & { data: { y: number[] }[] }).data[0]
    return t.y.length === values.length ? Math.max(...t.y.map((v, i) => Math.abs(v-values[i]))) : Infinity
  }, y)).toBeLessThan(1e-10)
}
async function inspect(page: Page) {
  await page.getByRole('button', { name: 'Import data', exact: true }).click()
  const inspecting = page.waitForResponse(r => r.url().endsWith('/inspect'))
  await page.getByLabel('Choose data files', { exact: true }).setInputFiles(fixture)
  const response = await inspecting; expect(response.ok()).toBe(true)
  return response.json()
}
async function preference(page: Page, enabled: boolean) {
  await page.getByRole('button', { name: 'File', exact: true }).click()
  await page.getByRole('button', { name: 'Beamline identification…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Beamline identification', exact: true })
  const toggle = dialog.getByRole('checkbox', { name: 'Identify beamline metadata on import' })
  await expect(toggle).toBeEnabled(); await toggle.setChecked(enabled)
  const saving = page.waitForResponse(r => r.url().endsWith('/preferences/beamline') && r.request().method() === 'PUT')
  await dialog.getByRole('button', { name: 'Save settings', exact: true }).click()
  expect((await saving).ok()).toBe(true)
  await expect(dialog.getByText(/Settings saved/)).toBeVisible()
  await dialog.getByRole('button', { name: 'Close settings', exact: true }).click()
}

test('measured X11A live columns, metadata, processing, PRJ restore and persisted identification preference', async ({ page }, info) => {
  test.setTimeout(90000)
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.setViewportSize({ width: 1500, height: 1040 }); await page.goto('/')
  const i = await inspect(page)
  expect(i.row_count).toBe(612); expect(i.columns.map((c: { name: string }) => c.name)).toEqual(['energy', 'I0', 'I', 'If'])
  const dialog = page.getByRole('dialog', { name: 'Import spectra', exact: true })
  const plot = dialog.getByLabel('Imported signal preview plot', { exact: true })
  const mu = rows.map(r => Math.log(r[1]/r[2]))
  await signal(plot, mu)
  const metadata = dialog.getByRole('region', { name: 'Beamline metadata', exact: true })
  await expect(metadata).toContainText('Acquired: 1992-09-15T01:52:53')
  await expect(dialog.getByText(/611 points; all 612 observed rows/).first()).toBeVisible()
  await metadata.getByText('View beamline metadata', { exact: true }).click()
  await expect(metadata).toContainText('3.135301'); await expect(metadata).toContainText('rolled and annealled')
  await dialog.screenshot({ path: info.outputPath('x11a-columns-metadata.png') })
  await dialog.getByRole('checkbox', { name: 'Numerator I0', exact: true }).uncheck()
  await dialog.getByRole('checkbox', { name: 'Numerator If', exact: true }).check()
  await dialog.getByRole('checkbox', { name: 'Denominator I', exact: true }).uncheck()
  await dialog.getByRole('checkbox', { name: 'Denominator I0', exact: true }).check()
  await dialog.getByRole('checkbox', { name: 'Natural log', exact: true }).uncheck()
  await signal(plot, rows.map(r => r[3]/r[1]))
  await expect(metadata).toContainText('1992-09-15T01:52:53')
  await dialog.getByRole('checkbox', { name: 'Numerator If', exact: true }).uncheck()
  await dialog.getByRole('checkbox', { name: 'Numerator I0', exact: true }).check()
  await dialog.getByRole('checkbox', { name: 'Denominator I0', exact: true }).uncheck()
  await dialog.getByRole('checkbox', { name: 'Denominator I', exact: true }).check()
  await dialog.getByRole('checkbox', { name: 'Natural log', exact: true }).check()
  await signal(plot, mu)
  const importing = page.waitForResponse(r => r.url().endsWith('/import'))
  await dialog.getByRole('button', { name: 'Import spectrum', exact: true }).click()
  const response = await importing; expect(response.ok()).toBe(true)
  const project = await response.json(), group = project.groups.at(-1)
  expect(group.processing_error).toBeNull(); expect(group.result.arrays.norm.length).toBe(612)
  expect(group.source.beamline_metadata).toEqual(i.beamline_metadata)
  expect(Object.values(group.source.column_arrays)).toEqual([0, 1, 2, 3].map(c => rows.map(r => r[c])))
  await expect(dialog).toHaveCount(0); await page.reload()
  await page.getByRole('button', { name: 'Edit group information', exact: true }).click()
  const groupInfo = page.getByRole('dialog', { name: 'Group information', exact: true })
  await expect(groupInfo.getByRole('region', { name: 'Beamline metadata' })).toContainText('1992-09-15T01:52:53')
  await groupInfo.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'File', exact: true }).click()
  const downloading = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Save Athena project (.prj)', exact: true }).click()
  const download = await downloading, path = info.outputPath('x11a.prj'); await download.saveAs(path)
  await page.getByRole('button', { name: 'File', exact: true }).click()
  await page.getByRole('button', { name: 'Open project', exact: true }).click()
  await page.getByLabel('Open project file', { exact: true }).setInputFiles(path)
  const restoring = page.waitForResponse(r => r.url().endsWith('/restore-upload'))
  await page.getByRole('button', { name: 'Import all groups', exact: true }).click()
  const restored = await restoring; expect(restored.ok()).toBe(true)
  expect((await restored.json()).groups.at(-1).source).toEqual(group.source)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await preference(page, false)
  await page.reload()
  const disabled = await inspect(page); expect(disabled.beamline_metadata).toBeUndefined()
  await expect(dialog.getByRole('region', { name: 'Beamline metadata' })).toHaveCount(0)
  await signal(plot, mu)
  await dialog.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await preference(page, true)
  expect(errors).toEqual([])
})

test('X11A acquisition fields and all measured points remain usable on mobile', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/')
  await inspect(page)
  const dialog = page.getByRole('dialog', { name: 'Import spectra', exact: true })
  await signal(dialog.getByLabel('Imported signal preview plot', { exact: true }), rows.map(r => Math.log(r[1]/r[2])))
  const metadata = dialog.getByRole('region', { name: 'Beamline metadata' })
  await metadata.getByText('View beamline metadata', { exact: true }).click()
  await metadata.scrollIntoViewIfNeeded()
  expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth+1)).toBe(true)
  await page.screenshot({ path: info.outputPath('x11a-mobile-metadata.png') })
})
