import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { gunzipSync } from 'node:zlib'
import { expect, test, type Page } from '@playwright/test'

const fixture = fileURLToPath(new URL('../../../backend/tests/fixtures/xdi-official-cu_metal_rt.xdi', import.meta.url))
async function metadata(page: Page) {
  await page.getByRole('button', { name: 'Group', exact: true }).click()
  await page.getByRole('button', { name: 'File metadata…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'File metadata', exact: true })
  await expect(dialog.getByLabel('XDI comments')).toBeEnabled()
  return dialog
}

for (const width of [1500, 390]) {
  test(`derived XDI history, native PRJ and source independence at ${width}px`, async ({ page }, info) => {
    test.setTimeout(90000)
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.setViewportSize({ width, height: width === 390 ? 844 : 1040 })
    const source = readFileSync(fixture, 'utf8').replace('# ///', '# Scan.end_time: 2001-06-26T22:31:31\n# Scan.process: Earlier processing\n# ///')
    await page.goto('/'); await page.getByRole('button', { name: 'Import data', exact: true }).click()
    await page.getByLabel('Choose data files', { exact: true }).setInputFiles({ name: 'Cu-history.xdi', mimeType: 'text/plain', buffer: Buffer.from(source) })
    await expect(page.getByRole('dialog').locator('.js-line').first()).toBeVisible()
    const importing = page.waitForResponse(r => r.url().endsWith('/import'))
    await page.getByRole('button', { name: 'Import spectrum', exact: true }).click()
    const imported = await importing; expect(imported.ok()).toBe(true)
    const initial = await imported.json()
    let dialog = await metadata(page)
    const comments = 'Reviewed μ 铜 "quoted" $literal @array\nSecond line'
    await dialog.getByLabel('XDI comments').fill(comments)
    const saving = page.waitForResponse(r => r.url().endsWith('/command') && r.request().postDataJSON().action === 'xdi_comments')
    await dialog.getByRole('button', { name: 'Save comments' }).click()
    const savedComments = await saving; expect(savedComments.ok()).toBe(true)
    const original = (await savedComments.json()).groups[0]
    await dialog.getByRole('button', { name: 'Close metadata' }).click()
    await page.getByRole('button', { name: 'Process', exact: true }).click()
    await page.getByRole('button', { name: 'Multi-electron excitation', exact: true }).click()
    const mee = page.getByRole('dialog', { name: 'Multi-electron excitation', exact: true })
    await mee.getByLabel('Algorithm', { exact: true }).selectOption('arctangent')
    await mee.getByLabel('Broadening (eV)', { exact: true }).fill('2')
    await mee.getByLabel('Energy shift (eV)', { exact: true }).fill('30')
    await expect(mee.getByRole('button', { name: 'Make group from MEE-corrected data' })).toBeEnabled()
    const making = page.waitForResponse(r => r.url().endsWith('/command') && r.request().postDataJSON().action === 'multi_electron')
    await mee.getByRole('button', { name: 'Make group from MEE-corrected data' }).click()
    const made = await making; expect(made.ok()).toBe(true)
    const project = await made.json(), child = project.groups[1]
    expect(project.groups[0]).toEqual(original)
    const history = 'Earlier processing; Removed multi-electron excitation'
    expect(child.source.xdi_metadata.attributes.scan.process).toBe(history)
    expect(child.source.xdi_metadata.comments_text).toBe(comments)
    dialog = await metadata(page)
    const panel = dialog.getByRole('region', { name: 'Acquisition and processing history' })
    await expect(panel.getByText(history, { exact: true })).toBeVisible()
    await expect(panel.getByText('2001-06-26T22:31:31', { exact: true })).toBeVisible()
    await expect(panel.getByText(/inherited from the source scan/)).toBeVisible()
    expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
    await dialog.evaluate(node => { node.scrollTop = 0 })
    await page.screenshot({ path: info.outputPath(`history-${width}.png`) })
    await dialog.getByRole('button', { name: 'Close metadata' }).click()
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Data groups 1', exact: true })).toBeVisible()
    dialog = await metadata(page)
    await expect(dialog.getByRole('region', { name: 'Acquisition and processing history' }).getByText('Earlier processing', { exact: true })).toBeVisible()
    await dialog.getByRole('button', { name: 'Close metadata' }).click()
    await page.getByRole('button', { name: 'Redo', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Data groups 2', exact: true })).toBeVisible()
    const downloading = page.waitForEvent('download')
    await page.getByRole('link', { name: 'Save project', exact: true }).click()
    const path = info.outputPath('derived-native.prj'); await (await downloading).saveAs(path)
    writeFileSync(path, gunzipSync(readFileSync(path)).toString('utf8').split('\n').filter(line => !line.startsWith('# Athena-Web ')).join('\n'))
    await page.getByRole('button', { name: 'File', exact: true }).click()
    await page.getByRole('button', { name: 'Open project…', exact: true }).click()
    await page.getByLabel('Open project file', { exact: true }).setInputFiles(path)
    const restoring = page.waitForResponse(r => r.url().endsWith('/restore-upload'))
    await page.getByRole('button', { name: 'Import all groups', exact: true }).click()
    const restored = await restoring; expect(restored.ok()).toBe(true)
    const reopened = (await restored.json()).groups.at(-1)
    expect(reopened.source.xdi_metadata.attributes.scan.process).toBe(history)
    expect(reopened.source.xdi_metadata.comments_text).toBe(comments)
    expect(reopened.mu).toEqual(child.mu)
    dialog = await metadata(page)
    await expect(dialog.getByRole('region', { name: 'Acquisition and processing history' }).getByText(history, { exact: true })).toBeVisible()
    await expect(dialog.getByLabel('XDI comments')).toHaveValue(comments)
    const checked = await page.request.get(`/api/backend/api/athena/projects/${initial.id}`)
    expect(checked.ok()).toBe(true)
    expect((await checked.json()).groups[0]).toEqual(original)
    expect(errors).toEqual([])
  })
}
