import { expect, test, type Locator } from '@playwright/test'
import { fileURLToPath } from 'node:url'

async function plotted(panel: Locator, space: 'E' | 'k') {
  const region = panel.getByLabel(`${space}-space rebin preview`, { exact: true })
  await expect(region).toHaveAttribute('aria-busy', 'false')
  const plot = region.locator('.js-plotly-plot')
  await expect(plot.locator('.js-line').first()).toBeAttached()
  return plot.evaluate(node => (node as HTMLElement & { data: { x: number[]; y: number[]; name: string }[] }).data.map(t => ({ x: [...t.x], y: [...t.y], name: t.name })))
}

test('Athena rebin previews measured E and k data, inserts current/marked groups, and undoes a whole batch', async ({ page }, info) => {
  test.setTimeout(90000)
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  const loaded = page.waitForResponse(r => r.url().endsWith('/command'))
  await page.getByRole('button', { name: 'Load copper foil example', exact: true }).click()
  const original = await (await loaded).json()
  await expect(page.getByRole('heading', { name: 'Data groups 3', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Process', exact: true }).click()
  await page.getByRole('button', { name: 'Rebin data', exact: true }).click()
  const panel = page.getByRole('dialog', { name: 'Rebin data' })
  await panel.getByLabel('Rebin source group').selectOption(original.groups[0].id)
  await expect.poll(async () => (await plotted(panel, 'E'))[0].name).toContain(original.groups[0].label)
  const ecurves = await plotted(panel, 'E')
  expect(ecurves).toHaveLength(2)
  expect(ecurves[0].x).toEqual(original.groups[0].energy)
  expect(ecurves[0].y).toEqual(original.groups[0].mu)
  expect(ecurves[1].x.length).toBeLessThan(ecurves[0].x.length)
  await panel.screenshot({ path: info.outputPath('rebin-energy-desktop.png') })
  const kResponse = page.waitForResponse(r => r.url().endsWith('/rebin/preview') && r.request().postDataJSON().options.plot_space === 'k')
  await panel.getByRole('button', { name: 'Plot data and rebinned data in k', exact: true }).click()
  const kp = await (await kResponse).json()
  const kcurves = await plotted(panel, 'k')
  expect(kcurves).toHaveLength(2)
  for (const [i, trace] of kp.results[0].traces.entries()) {
    expect(kcurves[i].x).toEqual(trace.x); expect(kcurves[i].y).toEqual(trace.y)
  }
  expect(kcurves[0].y).toEqual(original.groups[0].result.arrays.weighted_chi)
  const created = page.waitForResponse(r => r.url().endsWith('/command'))
  await panel.getByRole('button', { name: 'Make rebinned data group', exact: true }).click()
  const one = await (await created).json()
  expect(one.groups).toHaveLength(4)
  expect(one.groups[0]).toEqual(original.groups[0])
  expect(one.groups.slice(2)).toEqual(original.groups.slice(1))
  expect(one.groups[1].energy).toEqual(ecurves[1].x)
  expect(one.groups[1].mu).toEqual(ecurves[1].y)
  expect(one.groups[1].result.arrays.weighted_chi).toEqual(kcurves[1].y)
  expect(one.groups[1].marked).toBe(false)
  await expect(panel.getByRole('status').filter({ hasText: 'Created 1' })).toBeVisible()
  await panel.getByLabel('Preview marked groups (3)').check()
  await expect.poll(async () => (await plotted(panel, 'k')).length).toBe(6)
  const batchResponse = page.waitForResponse(r => r.url().endsWith('/command'))
  await panel.getByRole('button', { name: 'Rebin marked data and make groups', exact: true }).click()
  const batch = await (await batchResponse).json()
  expect(batch.groups).toHaveLength(7)
  expect(batch.last_operation.rebin_results).toHaveLength(3)
  for (const item of batch.last_operation.rebin_results) {
    const at = batch.groups.findIndex((g: { id: string }) => g.id === item.source_group_id)
    expect(batch.groups[at + 1].id).toBe(item.group_id)
    expect(batch.groups[at]).toEqual(original.groups.find((g: { id: string }) => g.id === item.source_group_id))
    expect(batch.groups[at + 1].processing_error).toBeNull()
  }
  await expect(panel.getByRole('status').filter({ hasText: 'Created 3' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await panel.getByLabel('Show original data').scrollIntoViewIfNeeded()
  await expect.poll(async () => panel.getByLabel('k-space rebin preview').evaluate(node => {
    const svg = node.querySelector('.main-svg')
    return svg ? Math.abs(svg.getBoundingClientRect().width - node.getBoundingClientRect().width) : 1000
  })).toBeLessThan(4)
  await panel.screenshot({ path: info.outputPath('rebin-k-mobile.png') })
  await panel.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Data groups 4', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Data groups 7', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Data groups 7', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('saved rebin grid is shared with import, survives a new browser session, and handles another window', async ({ page, browser }, info) => {
  test.setTimeout(90000)
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  const url = '/api/backend/api/athena/preferences/rebin'
  const original = await (await page.request.get(url)).json()
  try {
    await page.goto('/')
    await page.getByRole('button', { name: 'Load copper foil example', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Data groups 3', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Process', exact: true }).click()
    await page.getByRole('button', { name: 'Rebin data', exact: true }).click()
    let panel = page.getByRole('dialog')
    await expect(panel.getByRole('button', { name: 'Save grid as defaults' })).toBeEnabled()
    await panel.getByLabel('Pre-edge grid · eV', { exact: true }).fill('5')
    await panel.getByRole('button', { name: 'Save grid as defaults' }).click()
    await expect(panel.getByText('Grid defaults saved for future sessions.')).toBeVisible()
    const stored = await (await page.request.get(url)).json()
    expect(stored.grid.pre).toBe(5)
    expect(stored.grid).not.toHaveProperty('e0')
    await panel.getByRole('button', { name: 'Close dialog' }).click()
    await page.getByRole('button', { name: 'Import data', exact: true }).click()
    await page.getByLabel('Choose data files', { exact: true }).setInputFiles(fileURLToPath(new URL('../../../examples/xafsdata/cu_10k.xmu', import.meta.url)))
    panel = page.getByRole('dialog')
    await panel.getByText('Rebin quick scans', { exact: true }).click()
    await panel.getByRole('button', { name: 'Load saved grid' }).click()
    await expect(panel.getByLabel('Perform rebinning', { exact: true })).not.toBeChecked()
    await expect(panel.getByLabel('Rebin pre-edge step · eV', { exact: true })).toHaveValue('5')
    await panel.getByLabel('Perform rebinning', { exact: true }).check()
    await panel.getByLabel('Rebin pre-edge step · eV', { exact: true }).fill('7')
    await expect(panel.getByLabel('Imported signal preview plot')).toHaveAttribute('aria-busy', 'false')
    await expect(panel.getByLabel('Imported signal preview plot').locator('.js-line').first()).toBeAttached()
    await panel.getByRole('button', { name: 'Save grid as defaults' }).click()
    await expect(panel.getByText('Grid defaults saved for future sessions.')).toBeVisible()
    await panel.screenshot({ path: info.outputPath('shared-grid-import.png') })
    const other = await browser.newContext({ baseURL: info.project.use.baseURL })
    try {
      const tab = await other.newPage(); await tab.goto('/')
      await tab.getByRole('button', { name: 'Import data', exact: true }).click()
      await tab.getByLabel('Choose data files', { exact: true }).setInputFiles(fileURLToPath(new URL('../../../examples/xafsdata/cu_10k.xmu', import.meta.url)))
      const columns = tab.getByRole('dialog')
      await columns.getByText('Rebin quick scans', { exact: true }).click()
      await columns.getByRole('button', { name: 'Load saved grid' }).click()
      await expect(columns.getByLabel('Rebin pre-edge step · eV', { exact: true })).toHaveValue('7')
      await expect(columns.getByLabel('Perform rebinning', { exact: true })).not.toBeChecked()
      await expect(columns.getByLabel('Imported signal preview plot')).toHaveAttribute('aria-busy', 'false')
    } finally { await other.close() }
    const latest = await (await page.request.get(url)).json()
    const otherUpdate = await page.request.put(url, { data: { version: latest.version, grid: { ...latest.grid, pre: 8 } } })
    expect(otherUpdate.ok()).toBe(true)
    await panel.getByRole('button', { name: 'Save grid as defaults' }).click()
    await expect(panel.getByRole('alert')).toContainText('changed in another window')
    await expect(panel.getByLabel('Rebin pre-edge step · eV', { exact: true })).toHaveValue('7')
    await panel.getByRole('button', { name: 'Load saved grid' }).click()
    await expect(panel.getByLabel('Rebin pre-edge step · eV', { exact: true })).toHaveValue('8')
    await panel.getByRole('button', { name: 'Use Athena default grid' }).click()
    await expect(panel.getByLabel('Rebin pre-edge step · eV', { exact: true })).toHaveValue('10')
    expect((await (await page.request.get(url)).json()).grid.pre).toBe(8)
    await expect(panel.getByLabel('Imported signal preview plot')).toHaveAttribute('aria-busy', 'false')
    expect(errors).toEqual([])
  } finally {
    const latest = await (await page.request.get(url)).json()
    expect((await page.request.put(url, { data: { version: latest.version, grid: original.grid } })).ok()).toBe(true)
  }
})
