import { expect, test, type Locator } from "@playwright/test"

async function expectInViewport(tooltip: Locator) {
  await expect(tooltip).toBeVisible()
  expect(await tooltip.evaluate(element => {
    const bounds = element.getBoundingClientRect()
    return bounds.left >= 0 && bounds.top >= 0 && bounds.right <= innerWidth && bounds.bottom <= innerHeight
  })).toBe(true)
}

test("field instructions stay opt-in and usable at desktop and phone widths", async ({ page }, info) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.setViewportSize({ width: 1600, height: 1050 })
  await page.goto("/")
  await page.getByRole("button", { name: "Load copper examples", exact: true }).click()
  await expect(page.getByText("Cu₂O EXAFS example added", { exact: true })).toBeVisible({ timeout: 60_000 })
  await page.getByRole("tab", { name: "Processing", exact: true }).click()
  const rbkg = page.getByRole("spinbutton", { name: "Rbkg Å", exact: true })
  await expect(rbkg).toBeEnabled()
  const value = await rbkg.inputValue()
  await rbkg.focus()
  await expect(page.getByRole("tooltip")).toHaveCount(0)
  const toggle = page.getByRole("checkbox", { name: "Show instruction", exact: true })
  await expect(toggle).not.toBeChecked()
  await expect(page.locator("[data-section-help]")).toHaveCount(0)
  await toggle.check()
  const parameters = page.locator("#athena-processing-parameters")
  expect(await parameters.locator("[data-section-help]").count()).toBeGreaterThan(25)
  const help = page.getByRole("button", { name: "About Rbkg", exact: true })
  await help.focus()
  await expectInViewport(page.getByRole("tooltip"))
  await expect(page.getByRole("tooltip")).toContainText("AUTOBK")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("tooltip")).toHaveCount(0)
  await expect(help).toBeFocused()
  await page.screenshot({ path: info.outputPath("processing-instructions-desktop.png") })
  await page.getByRole("tab", { name: "EXAFS fitting", exact: true }).click()
  const fittingHelp = page.getByRole("button", { name: "About Fit space", exact: true })
  await expect(fittingHelp).toBeVisible()
  await fittingHelp.focus()
  await expectInViewport(page.getByRole("tooltip"))
  await page.keyboard.press("Escape")
  await page.screenshot({ path: info.outputPath("fitting-instructions-desktop.png") })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("tab", { name: "Processing", exact: true }).click()
  await help.scrollIntoViewIfNeeded()
  await help.click()
  await expectInViewport(page.getByRole("tooltip"))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("field-instructions-mobile.png") })
  await page.keyboard.press("Escape")
  await toggle.uncheck()
  await expect(page.locator("[data-section-help]")).toHaveCount(0)
  await expect(rbkg).toHaveValue(value)
  expect(errors).toEqual([])
})
