import { expect, test, type Locator } from "@playwright/test"

async function expectTooltipInViewport(tooltip: Locator) {
  await expect(tooltip).toBeVisible()
  expect(await tooltip.evaluate(element => {
    const rect = element.getBoundingClientRect()
    return rect.left >= 0 && rect.top >= 0 && rect.right <= innerWidth && rect.bottom <= innerHeight
  })).toBe(true)
}

test("section descriptions stay compact and help works across panels, modal dialogs and narrow screens", async ({ page }, info) => {
  test.setTimeout(150_000)
  const errors: string[] = []
  const mutations: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.setViewportSize({ width: 1600, height: 1050 })
  await page.goto("/")
  await expect(page.getByRole("button", { name: "Load copper examples", exact: true })).toBeEnabled()
  const credits = page.getByRole("button", { name: "About Larch-Web", exact: true })
  await credits.focus()
  await expect(page.getByRole("tooltip")).toBeVisible()
  await page.keyboard.press("Tab")
  await expect(page.getByRole("link", { name: "Xraylarch", exact: true })).toBeFocused()
  await page.keyboard.press("Tab")
  await expect(page.getByRole("link", { name: "Demeter", exact: true })).toBeFocused()
  await page.keyboard.press("Tab")
  await expect(page.getByRole("tooltip")).toHaveCount(0)
  await page.getByRole("button", { name: "Load copper examples", exact: true }).click()
  const fitting = page.getByRole("region", { name: "Artemis EXAFS fitting setup" })
  const help = fitting.getByRole("button", { name: "About FEFF paths", exact: true })
  await expect(help).toBeVisible()
  await expect(page.getByText(/N is fixed by FEFF; the amplitude/)).toBeHidden()
  const size = await help.boundingBox()
  expect(size?.width).toBe(20)
  expect(size?.height).toBe(20)
  const pathSection = help.locator("xpath=ancestor::details[1]")
  await expect(pathSection).toHaveAttribute("open", "")
  await help.hover()
  const tooltip = page.getByRole("tooltip")
  await expectTooltipInViewport(tooltip)
  await expect(tooltip).toContainText("N is fixed by FEFF")
  await page.keyboard.press("Escape")
  await expect(tooltip).toHaveCount(0)
  await help.focus()
  await expectTooltipInViewport(tooltip)
  await page.keyboard.press("Enter")
  await expect(pathSection).toHaveAttribute("open", "")
  await page.keyboard.press("Escape")
  await fitting.screenshot({ path: info.outputPath("compact-fitting-desktop.png") })

  await fitting.getByRole("button", { name: "Open attached Cuprite CIF", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Crystal structures & FEFF paths" })
  const dialogHelp = dialog.getByRole("button", { name: "About Crystal structures and FEFF paths", exact: true })
  await dialogHelp.hover()
  await expectTooltipInViewport(dialog.getByRole("tooltip"))
  expect(await dialog.getByRole("tooltip").evaluate(element => {
    const rect = element.getBoundingClientRect()
    return element.contains(document.elementFromPoint(rect.left + 12, rect.top + 12))
  })).toBe(true)
  await page.keyboard.press("Escape")
  await expect(dialog).toBeVisible()
  await dialog.getByRole("radio", { name: "Absorber site 1", exact: true }).click()
  await dialog.getByRole("button", { name: "Close CIF search", exact: true }).click()
  const radial = fitting.getByRole("region", { name: "Radial shells", exact: true })
  await expect(radial).toBeVisible()
  await expect(page.getByText(/Distances are measured from the selected absorber/).first()).toBeHidden()
  await radial.getByRole("button", { name: "About Radial shells", exact: true }).hover()
  await expectTooltipInViewport(tooltip)
  await expect(tooltip).toContainText("structural ranges")
  await page.keyboard.press("Escape")

  page.on("request", request => {
    if (request.method() !== "GET" && /\/(command|model|fit|fit-saved)(?:\?|$)/.test(request.url())) mutations.push(request.url())
  })
  await page.setViewportSize({ width: 390, height: 844 })
  await help.scrollIntoViewIfNeeded()
  await help.click()
  await expectTooltipInViewport(tooltip)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("compact-help-mobile.png") })
  expect(mutations).toEqual([])
  expect(errors).toEqual([])
})
