#!/usr/bin/env python3
"""Generate TypeScript declarations for the persistent v2 integration contract."""
from __future__ import annotations

import argparse
from pathlib import Path

from xraylarch_web.integration_contracts import (
    AuthoritativeSpectrum,
    AthenaUploadedSource,
    AutobkParameters,
    CoreProcessingRecipe,
    ExistingDrXasSource,
    ExportReservation,
    ForwardFtParameters,
    NormalizationParameters,
    ProjectBootstrapRequest,
    ProjectLaunch,
    ProjectQuota,
    ProjectSeed,
    ProjectSummary,
    ReverseFtParameters,
    SelectedGroupExportBatch,
    SelectedGroupExportRequest,
    SelectedGroupRef,
)

MODELS = (
    AuthoritativeSpectrum,
    NormalizationParameters,
    AutobkParameters,
    ForwardFtParameters,
    ReverseFtParameters,
    CoreProcessingRecipe,
    ProjectSeed,
    ProjectBootstrapRequest,
    ProjectLaunch,
    ProjectSummary,
    SelectedGroupRef,
    SelectedGroupExportRequest,
    SelectedGroupExportBatch,
    ExistingDrXasSource,
    AthenaUploadedSource,
    ExportReservation,
    ProjectQuota,
)
OUTPUT = Path(__file__).resolve().parents[1] / "frontend/lib/generated/integration-contracts.ts"


def type_for(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return repr(schema["const"])
    if "enum" in schema:
        return " | ".join(repr(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(type_for(option) for option in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(type_for(option) for option in schema["oneOf"])
    if schema.get("type") == "array":
        return f"ReadonlyArray<{type_for(schema.get('items', {}))}>"
    if schema.get("type") == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Readonly<Record<string, {type_for(additional)}>>"
        return "Readonly<Record<string, unknown>>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(schema.get("type"), "unknown")


def declaration(model: type) -> str:
    schema = model.model_json_schema()
    properties = schema["properties"]
    required = set(schema.get("required", ()))
    lines = [f"export interface {model.__name__} {{"]
    for name in sorted(properties):
        marker = "" if name in required else "?"
        lines.append(f"  readonly {name}{marker}: {type_for(properties[name])};")
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    declarations = "\n\n".join(declaration(model) for model in MODELS)
    return (
        "// Generated by scripts/generate-integration-contracts.py; do not edit.\n"
        "// Persistent integration v2 wire contract.\n\n"
        "export interface JsonObject { readonly [key: string]: JsonValue; }\n"
        "export type JsonValue = null | boolean | number | string | ReadonlyArray<JsonValue> | JsonObject;\n\n"
        f"{declarations}\n\n"
        "export type ProjectSource = ExistingDrXasSource | AthenaUploadedSource;\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("integration contract declarations are stale; run the generator")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
