import { describe, expect, it } from "vitest"
import type { ArtemisModelDraft, ArtemisPath } from "./artemis"
import { planCoordinationInsertion, type CoordinationOptions } from "./artemis-coordination"

const options: CoordinationOptions = { value: "3", s02: "0.9", refine: true, max: "6" }
function draft(): ArtemisModelDraft {
  return { revision: 1, transform: {} as ArtemisModelDraft["transform"],
    parameters: [{ id: "amp", name: "amp", kind: "guess", value: "0.8", min: "0", max: "2", expression: "" }],
    paths: [{ id: "p", label: "Cu–S", enabled: true, filename: "feff0001.dat", content: "unchanged FEFF contents",
      metadata: { reff: 2.1916, degen: 3, nleg: 2, absorber: "Cu", edge: "K", geometry: [], kmin: 0, kmax: 20 },
      sigma2: "0.003", s02: "amp", e0: "0", deltar: "0" }] }
}

describe("coordination number insertion", () => {
  it("creates a bounded CN and fixed S₀² while preserving the FEFF file, metadata, and original draft", () => {
    const before = draft()
    const result = planCoordinationInsertion(before, "p", options)
    expect(result.expression).toBe("s02_1 * cn_1 / degen")
    expect(result.coordinationName).toBe("cn_1")
    expect(result.amplitudeName).toBe("s02_1")
    expect(result.added).toEqual([
      { name: "cn_1", kind: "guess", value: 3, min: 0, max: 6, expression: "" },
      { name: "s02_1", kind: "set", value: .9, min: null, max: null, expression: "" },
    ])
    expect(result.removed).toEqual(["amp"])
    expect(result.paths[0]).toEqual({ ...before.paths[0], s02: result.expression })
    expect(result.paths[0].metadata).toBe(before.paths[0].metadata)
    expect(before).toEqual(draft())
  })

  it("normalizes the FEFF amplitude once, so fitted coordination is independent of nominal degeneracy", () => {
    for (const degen of [3, 6, 12]) {
      const before = draft()
      before.paths[0].metadata.degen = degen
      const result = planCoordinationInsertion(before, "p", { ...options, value: "2.4" })
      const values = Object.fromEntries(result.added.map(parameter => [parameter.name, parameter.value]))
      // Evaluate only the expression generated by the helper; the native path adds its own degen factor.
      const evaluate = new Function(...Object.keys(values), "degen", `return ${result.expression}`)
      expect(degen * evaluate(...Object.values(values), degen)).toBeCloseTo(2.4 * .9, 12)
    }
  })

  it("preserves shared amplitudes and their constraints on other included paths", () => {
    const before = draft()
    before.paths.push({ ...before.paths[0], id: "other" })
    const shared = structuredClone(before.parameters[0])
    const result = planCoordinationInsertion(before, "p", options)
    expect(result.removed).toEqual([])
    expect(result.paths[1]).toBe(before.paths[1])
    expect(before.parameters[0]).toEqual(shared)
    expect(result.added.some(parameter => parameter.name === "amp")).toBe(false)
  })

  it("reserves existing names and unsynchronized expression names, even on excluded paths", () => {
    const before = draft()
    before.parameters.push({ ...before.parameters[0], id: "coord", name: "cn_1", kind: "def", expression: "cn_2 + 1" })
    before.paths.push({ ...before.paths[0], id: "other", enabled: false,
      s02: "s02_1 * cn_3 / degen", e0: "s02_2", deltar: "cn_4", sigma2: "s02_3" })
    const result = planCoordinationInsertion(before, "p", options)
    expect(result.expression).toBe("s02_4 * cn_5 / degen")
    expect(result.paths[1]).toBe(before.paths[1])
  })

  it("supports fixed or zero coordination, optional bounds, and S₀² above one without arbitrary clipping", () => {
    const fixed = planCoordinationInsertion(draft(), "p", { ...options, value: "0", s02: "1.1", refine: false, max: "invalid" })
    expect(fixed.added[0]).toMatchObject({ kind: "set", value: 0, min: null, max: null })
    expect(fixed.added[1].value).toBe(1.1)
    const unbounded = planCoordinationInsertion(draft(), "p", { ...options, max: "" })
    expect(unbounded.added[0]).toMatchObject({ kind: "guess", min: 0, max: null })
    expect(planCoordinationInsertion(draft(), "p", { ...options, max: "3" }).added[0].max).toBe(3)
  })

  it("rejects unsupported paths and invalid values without changing the draft", () => {
    const changes: Partial<CoordinationOptions>[] = [
      { value: "" }, { value: "-1" }, { value: "NaN" }, { value: "Infinity" },
      { s02: "" }, { s02: "0" }, { s02: "-0.9" }, { s02: "Infinity" },
      { max: "0" }, { max: "2" }, { max: "NaN" }, { max: "Infinity" },
    ]
    for (const change of changes) {
      const before = draft()
      expect(() => planCoordinationInsertion(before, "p", { ...options, ...change })).toThrow()
      expect(before).toEqual(draft())
    }
    expect(() => planCoordinationInsertion(draft(), "missing", options)).toThrow(/Include this path/)
    for (const change of [{ enabled: false }, { metadata: undefined },
      ...[0, -1, Infinity, NaN].map(degen => ({ metadata: { ...draft().paths[0].metadata, degen } })),
      { metadata: { ...draft().paths[0].metadata, nleg: 3 } }]) {
      const before = draft()
      before.paths[0] = { ...before.paths[0], ...change } as ArtemisPath
      const snapshot = structuredClone(before)
      expect(() => planCoordinationInsertion(before, "p", options)).toThrow()
      expect(before).toEqual(snapshot)
    }
  })

  it("keeps syntax and parameter-capacity failures atomic", () => {
    const invalid = draft()
    invalid.paths[0].e0 = "unfinished +"
    const snapshot = structuredClone(invalid)
    expect(() => planCoordinationInsertion(invalid, "p", options)).toThrow(/Cannot sync expression/)
    expect(invalid).toEqual(snapshot)

    const full = draft()
    full.paths[0].e0 = Array.from({ length: 31 }, (_, i) => `p${i}`).join("+")
    const fullSnapshot = structuredClone(full)
    expect(() => planCoordinationInsertion(full, "p", options)).toThrow(/limit is 32/)
    expect(full).toEqual(fullSnapshot)
  })
})
